version: '2.4'
services:
  backend-app:
    build: .
    env_file:
      - ./.env.dev
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - app_images_data:/opt/app/images
      - app_temp_data:/tmp/files

volumes:
  app_images_data:
  app_temp_data: