services:
  # 1. Serviço de Banco de Dados MySQL
  db:
    image: mysql:8.0
    container_name: system_db_dev
    restart: always
    environment:
      MYSQL_USER: appuser
      MYSQL_PASSWORD: vyHYPA7lYvBnP
      MYSQL_DATABASE: system
      MYSQL_ROOT_PASSWORD: 5c77q3zSRn
    ports:
      - "13306:3306" # Permite acesso de ferramentas locais ou do host
    volumes:
      - ./data/mysql:/var/lib/mysql
    healthcheck: # Adicionando healthcheck para garantir que o MySQL esteja pronto
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p5c77q3zSRn"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network # Anexa o DB à rede compartilhada

  # 2. Serviço phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: system_phpmyadmin_dev
    restart: always
    depends_on:
      db:
        condition: service_healthy # Espera o DB estar saudável
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 5c77q3zSRn
    ports:
      - "8181:80"
    networks:
      - app-network # Anexa o phpMyAdmin à rede compartilhada

networks:
  app-network:
    name: app-network # O nome da rede deve ser o mesmo usado no outro arquivo
    external: true           # A rede já deve ter sido criada pelo outro arquivo
